### ISSUE TITLE
Currently aao do not exists such scripts

### ISSUE THREAD

**Issue by Anduin2017** [NEUP-Net-Depart/FuckAAO#1]

**Comment by hudson6666** [comment]
Cool!

**Comment by Anduin2017** [comment]
Sooo, shall we delete this repository?

**Comment by hudson6666** [comment]
Well, emmm... I don't think "delete one repository" is a good idea in general?

**Comment by l2dy** [comment]
view-source:https://aao.neu.edu.cn/
```
<body onmousemove=/HideMenu()/ oncontextmenu="return false" 
ondragstart="return false" onselectstart ="return false" 
onselect="document.selection.empty()" 
oncopy="document.selection.empty()" onbeforecopy="return false">
```

**Comment by hudson6666** [comment]
@l2dy I started this extension in purpose of helping from the annoying 'alert' while using. If you need something to help enable copy, I would recommend seaching 'enable copy' in Chrome extension store. If you would like to contribute, further discussion or a pull request is welcomed.
